# Umbrel App Manifest
version: 1

metadata:
  category: finance
  name: WealthHub
  description: Modern portfolio management application to track your wealth
  version: 2.0.0
  icon: umbrel/icon.svg
  website: https://github.com/marpemad/wealthHub
  repository: https://github.com/marpemad/wealthHub
  support: https://github.com/marpemad/wealthHub/issues

containers:
  main:
    image: wealthhub:latest
    environment:
      VITE_GAS_URL: ${VITE_GAS_URL}
    ports:
      - "8787:3000"
    volumes:
      - data:/app/data

volumes:
  data:

